//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package layers 

{
	import org.flixel.FlxSprite;
	import org.flixel.FlxTilemap;
	
	public class MapBase {
		//Layer name definitions
		public static const LAYER_FOREGROUND:uint = 0;
		public static const LAYER_BACKGROUND:uint = 1;
		public static const LAYER_MAP:uint = 2;
	public static const LAYER_FARAWAY:uint = 3;
		//Layer variable accessors
		public var layerForeground:FlxTilemap;
		public var layerBackground:FlxTilemap;
		public var layerMap:FlxTilemap;
	public var layerFaraway:FlxTilemap;
	//	public var layerFaraway:FlxSprite;
		//Map layers and principal layer (map) declarations
		public var allLayers:Array;

		public var mainLayer:FlxTilemap;

		public var boundsMinX:int;
		public var boundsMinY:int;
		public var boundsMaxX:int;
		public var boundsMaxY:int;

		public function MapBase() { }

		public var bgColor:uint = 0xff464646;

		virtual public function addSpritesToLayerForeground(onAddCallback:Function = null):void { }
		virtual public function addSpritesToLayerBackground(onAddCallback:Function = null):void { }
		virtual public function addSpritesToLayerMap(onAddCallback:Function = null):void { }
		virtual public function addSpritesToLayerFaraway(onAddCallback:Function = null):void { }
		public var customValues:Object = new Object;		//Name-value map;
		virtual public function customFunction(param:* = null):* { }

	}
}
